version: '3'

services:
  spring-cloud-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - sub-service
      - course-service
      - teacher-service
    networks:
      - gradeHoraria

  course-service:
    image: api_courses-app
    ports:
      - "3000:3000"
    depends_on:
    - keycloak
    command: npm start
    networks:
      - gradeHoraria

  teacher-service:
    image: api_teacher-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sggh_teacher
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/gradeHoraria
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/gradeHoraria/protocol/openid-connect/certs
    depends_on:
      - db
      - keycloak
    command: java -jar api_teacher.jar
    networks:
      - gradeHoraria

  sub-service:
    image: cake-web
    ports:
      - "8765:80"
    depends_on:
      - db_mysql
      - keycloak
    volumes:
      - /var/www/html
      - ./logs:/var/www/html/logs
      - ./cache:/var/www/html/tmp/cache
    networks:
      - gradeHoraria

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - gradeHoraria

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sggh_teacher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - gradeHoraria   

  db_mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: sggh_subjects
    volumes:
      - ./init_create_table.sql:/docker-entrypoint-initdb.d/init_create_table.sql
    ports:
      - "3306:3306"
    networks:
    - gradeHoraria

networks:
  gradeHoraria:
    driver: bridge

volumes:
  postgres_data:


